name: Docker Image CI & Cloud Deployment CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dataframe-java:latest
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Tag Docker image
      run: |
        docker tag dataframe-java:latest alibay07/dataframe-java:latest
        
    - name: Push Docker image to Docker Hub
      run: docker push alibay07/dataframe-java:latest
      
  deployment:
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    
    - name: Deployment using ssh 
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 35.192.5.188
        username: dev
        key: ${{ secrets.SSH_SECRET }}
        port: 22
        script: |
          sudo docker pull alibay07/dataframe-java 
          sudo docker images | grep alibay |grep -v latest | cut -d' ' -f8 | xargs -r docker rmi -f
