name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dataframe-java:$(date +%s)

    - name: Debug secrets
      run: |
        echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}"
        echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Tag Docker image
      run: docker tag dataframe-java:$(date +%s) alibay07/dataframe-java:latest
    
    - name: Push Docker image to Docker Hub
      run: docker push alibay07/dataframe-java:latest
