name: Docker Image CI & Cloud Deployment CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dataframe-java:latest
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Tag Docker image
      run: |
        docker tag dataframe-java:latest alibay07/dataframe-java:latest
        
    - name: Push Docker image to Docker Hub
      run: docker push alibay07/dataframe-java:latest
  deployment:
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with: 
        ssh-private-key: ${{ secrets.SSH_SECRET }}

    - name: Connect to VM
      run: ssh dev@35.192.5.188

    - name: Docker pull
      run: sudo docker pull alibay07/dataframe-java
