name: Maven Build and Test

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B compile --file pom.xml

    - name: Run Tests
      run: mvn -B test --file pom.xml

    - name: Generate coverage badge
      uses: pooi/coverage-badge@1.0.0
      with:
        token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        xml-test-report-path: ${SOURCE_PATH}/target/site/jacoco/jacoco.xml
        html-test-report-path: ${SOURCE_PATH}/target/site/jacoco/index.html