name: Maven Build and Test

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

      - name: Maven Dependency Tree Dependency Submission
      uses: advanced-security/maven-dependency-submission-action@v4.0.2
      run: maven-dependency-submission -d ../..

    - name: Build with Maven
      run: mvn -B compile --file pom.xml

    - name: Run Tests
      run: mvn -B test --file pom.xml
