name: Build and Deploy Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
   
      - name: Increment Snapshot Version
        id: increment-version
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          incremented_version=$(echo $current_version | awk -F'[-]' '{split($1,a,"."); print a[1]+1"."a[2]"-SNAPSHOT"}')
          mvn versions:set -DnewVersion=${incremented_version} -DgenerateBackupPoms=false
          echo "::set-output name=new_version::$incremented_version"

      - name: Commit Version Increment
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add pom.xml
          git commit -m "Incremented snapshot version to ${{ steps.increment-version.outputs.new_version }}"
          git push origin HEAD:main

      - name: Deploy to GitHub Packages
        run: mvn --batch-mode deploy -DrepositoryId=github -Durl=https://maven.pkg.github.com/AliBay07/dataframe-java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
